export interface Produit {
   
    ID: any,
    produit_special_b?:string,
    variete_poids_a:any
    prixEscompte:any,
    prix_vente_variete_r:any,
    categorie_a:any,
    input0_lundi?:any,
    input0_mardi?:any,
    input0_mercredi?:any,
    input0_jeudi?:any,
    input0_vendredi?:any,
    input0_samedi?:any,
    input0_dimanche?:any,
    produit_lundi_b:any,
    produit_mardi_b:any,
    produit_mercredi_b:any,
    produit_jeudi_b:any,
    produit_vendredi_b:any,
    produit_samedi_b:any,
    produit_dimanche_b:any,
    totalCommande?:number,
    url_image?:string,
    codeClient:number,
    dateLundi:string,
    invendus:boolean,
    lundi:any,
    qteMinCommande?:number,
    nom:string,
    prenom:string,
    telephone:string,
    courriel:string,
    lieu:string,
    heureRupture: number,
    paye: boolean,
    deuxCuissons?:boolean
    input0_lundiCuisson1?:number,
    input0_mardiCuisson1?:number,
    input0_mercrediCuisson1?:number,
    input0_jeudiCuisson1?:number,
    input0_vendrediCuisson1?:number,
    input0_samediCuisson1?:number,
    input0_dimancheCuisson1?:number,
    commentaires?:string
    }